avisappadmin_homepage:
    pattern:  /admin
    defaults: { _controller: avisappadminBundle:Default:index }

vistaPrincipal:
    pattern: /admin/vistaPrincipal
    defaults: {_controller: avisappadminBundle:Default:vistaPrincipal}


avisappadminBundle_usuario:
        resource: "@avisappadminBundle/Resources/config/routing/usuario.yml"
        prefix:   /admin/usuario

        
avisappadminBundle_admin_slider:
        resource: "@avisappadminBundle/Resources/config/routing/slider.yml"
        prefix:   /admin/slider

avisappadminBundle_admin_caluga:
        resource: "@avisappadminBundle/Resources/config/routing/caluga.yml"
        prefix:   /admin/caluga


avisappadminBundle_admin_textoquees:
        resource: "@avisappadminBundle/Resources/config/routing/textoquees.yml"
        prefix:   /admin/textoquees
        
        
login:
   pattern:  /admin/login
   defaults: { _controller: avisappadminBundle:Default:login }

avisappadminBundle_admin_calugabeneficio:
        resource: "@avisappadminBundle/Resources/config/routing/calugabeneficio.yml"
        prefix:   /admin/calugabeneficio

avisappadminBundle_admin_botonhome:
        resource: "@avisappadminBundle/Resources/config/routing/botonhome.yml"
        prefix:   /admin/botonhome
        
avisappadminBundle_admin_textoqueesdos:
        resource: "@avisappadminBundle/Resources/config/routing/textoqueesdos.yml"
        prefix:   /admin/textoqueesdos

        


