avisappadmin_homepage:
    pattern:  /admin
    defaults: { _controller: avisappadminBundle:Default:index }

vistaPrincipal:
    pattern: /admin/vistaPrincipal
    defaults: {_controller: avisappadminBundle:Default:vistaPrincipal}


avisappadminBundle_usuario:
        resource: "@avisappadminBundle/Resources/config/routing/usuario.yml"
        prefix:   /admin/usuario

        
avisappadminBundle_admin_slider:
        resource: "@avisappadminBundle/Resources/config/routing/slider.yml"
        prefix:   /admin/slider

